name       : blender
version    : 2.79b
release    : 33
source     :
    - https://download.blender.org/source/blender-2.79b.tar.gz : 4c944c304a49e68ac687ea06f5758204def049b66dc211e1cffa1857716393bc
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : A fully integrated 3D graphics creation suite
description: |
    Blender is the free and open source 3D creation suite. It supports the entirety of the 3D pipeline—modeling, rigging, animation, simulation, rendering, compositing and motion tracking, even video editing and game creation.
builddeps  :
    - pkgconfig(fftw3f)
    - pkgconfig(freetype2)
    - pkgconfig(glew)
    - pkgconfig(jemalloc)
    - pkgconfig(libavcodec)
    - pkgconfig(libopenjp2)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(openal)
    - pkgconfig(OpenColorIO)
    - pkgconfig(OpenEXR)
    - pkgconfig(python3)
    - pkgconfig(sdl2)
    - pkgconfig(sndfile)
    - pkgconfig(xi)
    - libboost-devel
    - llvm-devel
    - openimageio-devel
setup      : |
    %patch -p1 < $pkgfiles/0007-fix_OpenJPEG2_build.patch

    mkdir build && pushd build
    # Need python3.4 for blender, gotta get this updated (task4 ikey)
    # Lots of enabling to do here, system glew, bullet, openjpeg, gameengine, etc..
    # importantly: fix clang, get llvm working here.
    %cmake .. \
        -DPYTHON_LIBPATH=%libdir% \
        -DPYTHON_LIBRARY=python3.6m \
        -DPYTHON_INCLUDE_DIR=/usr/include/python3.6m \
        -DWITH_INSTALL_PORTABLE=OFF \
        -DWITH_PYTHON_INSTALL=OFF \
        -DWITH_SDL=ON \
        -DWITH_IMAGE_OPENJPEG=ON \
        -DWITH_SYSTEM_OPENJPEG=ON \
        -DWITH_OPENCOLORIO=ON \
        -DWITH_FFTW3=ON \
        -DWITH_X11_XINPUT=ON \
        -DWITH_SDL_DYNLOAD=ON \
        -DWITH_CODEC_FFMPEG=ON \
        -DWITH_CODEC_SNDFILE=ON \
        -DWITH_SYSTEM_GLEW=ON \
        -DWITH_LLVM=ON
build      : |
    %make -C build
install    : |
    %make_install -C build
