name       : blender
version    : 3.4.1
release    : 70
source     :
    - https://download.blender.org/source/blender-3.4.1.tar.xz : 247c4c1228270c9010f4721c985cb5b628ab50abcf9f2678630737142eeb91c3
license    : GPL-2.0-or-later
homepage   : https://blender.org/
component  : multimedia.graphics
summary    : A fully integrated 3D graphics creation suite
description: |
    Blender is the free and open source 3D creation suite. It supports the entirety of the 3D pipeline—modeling, rigging, animation, simulation, rendering, compositing and motion tracking, even video editing and game creation.
builddeps  :
    - pkgconfig(OpenColorIO)
    - pkgconfig(OpenEXR)
    - pkgconfig(OpenImageIO)
    - pkgconfig(epoxy)
    - pkgconfig(fftw3f)
    - pkgconfig(freetype2)
    - pkgconfig(jack)
    - pkgconfig(jemalloc)
    - pkgconfig(libavcodec)
    - pkgconfig(libopenjp2)
    - pkgconfig(libpulse)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libzstd)
    - pkgconfig(lzo2)
    - pkgconfig(openal)
    - pkgconfig(oslcomp)
    - pkgconfig(libpcre)
    - pkgconfig(pugixml)
    - pkgconfig(python3)
    - pkgconfig(sdl2)
    - pkgconfig(sndfile)
    - pkgconfig(tbb)
    - pkgconfig(xi)
    - pkgconfig(xrender)
    - pkgconfig(xxf86vm)
    - alembic-devel
    - embree-devel
    - libboost-devel
    - libharu-devel
    - llvm-devel
    - numpy
    - potrace-devel
    - opencollada-devel
    - openimagedenoise-devel
    - opensubdiv-devel
    - openvdb-devel
rundeps    :
    - opencollada
clang      : no
setup      : |
    %cmake_ninja \
        -DPYTHON_VERSION=%python3_version% \
        -DPYTHON_LIBPATH=%libdir% \
        -DPYTHON_LIBRARY=python%python3_version% \
        -DPYTHON_INCLUDE_DIR=/usr/include/python%python3_version% \
        -DWITH_ALEMBIC=ON \
        -DWITH_CODEC_FFMPEG=ON \
        -DWITH_CODEC_SNDFILE=ON \
        -DWITH_CYCLES_EMBREE=ON \
        -DWITH_CYCLES_OSL=ON \
        -DWITH_FFTW3=ON \
        -DWITH_HARU=ON \
        -DWITH_IMAGE_OPENJPEG=ON \
        -DWITH_INSTALL_PORTABLE=OFF \
        -DWITH_JACK=ON \
        -DWITH_LLVM=ON \
        -DWITH_OPENCOLORIO=ON \
        -DWITH_OPENIMAGEIO=ON \
        -DWITH_OPENSUBDIV=ON \
        -DWITH_OPENVDB=ON \
        -DWITH_POTRACE=ON \
        -DWITH_PULSEAUDIO=ON \
        -DWITH_PYTHON_INSTALL=OFF \
        -DWITH_SDL=ON \
        -DWITH_SYSTEM_GLEW=ON \
        -DWITH_SYSTEM_LZO=ON \
        -DWITH_USD=ON \
        -DWITH_X11_XINPUT=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    %python3_compile $installdir/usr/share/blender
    install -Dm00644 $pkgfiles/blender.thumbnailer -t $installdir/usr/share/thumbnailers
    rm -r $installdir/usr/share/doc/blender/license/
