name       : blender
version    : 2.76
release    : 3
source     :
    - http://download.blender.org/source/blender-2.76.tar.gz : 5b99649a89bdcd53bef8e668fbf2be5b3e9611f52f9e9c5f7e7c814c778e5835
license    : GPL-2.0+
summary    : A fully integrated 3D graphics creation suite
description: |
    A fully integrated 3D graphics creation suite
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(libpng)
    - pkgconfig(python-3.4)
    - pkgconfig(OpenEXR)
    - pkgconfig(libtiff-4)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - libjpeg-turbo-devel
    - jemalloc-devel
    - libboost-devel
    - openimageio-devel
clang      : no
setup      : |
    mkdir build && pushd build
    # Need python3.4 for blender, gotta get this updated (task4 ikey)
    # Lots of enabling to do here, system glew, bullet, openjpeg, gameengine, etc..
    # importantly: fix clang, get llvm working here.
    %cmake .. \
        -DPYTHON_LIBPATH=%libdir% \
        -DPYTHON_LIBRARY=python3.4m \
        -DPYTHON_INCLUDE_DIR=/usr/include/python3.4m \
        -DWITH_SYSTEM_GLEW=no \
        -DWITH_INSTALL_PORTABLE=OFF \
        -DWITH_PYTHON_INSTALL=OFF

build      : |
    pushd build
    %make
install    : |
    pushd build
    %make_install
    popd
