name       : blender
version    : 2.92.0
release    : 56
source     :
    - https://download.blender.org/source/blender-2.92.0.tar.xz : e791cfc403292383577c3c8ce2cd34e5aa2cd8da0a7483041049a1609ddb4595
license    : GPL-2.0-or-later
homepage   : https://blender.org/
component  : multimedia.graphics
summary    : A fully integrated 3D graphics creation suite
description: |
    Blender is the free and open source 3D creation suite. It supports the entirety of the 3D pipeline—modeling, rigging, animation, simulation, rendering, compositing and motion tracking, even video editing and game creation.
builddeps  :
    - pkgconfig(OpenColorIO)
    - pkgconfig(OpenEXR)
    - pkgconfig(OpenImageIO)
    - pkgconfig(fftw3f)
    - pkgconfig(freetype2)
    - pkgconfig(glew)
    - pkgconfig(jack)
    - pkgconfig(jemalloc)
    - pkgconfig(libavcodec)
    - pkgconfig(libopenjp2)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(lzo2)
    - pkgconfig(openal)
    - pkgconfig(oslcomp)
    - pkgconfig(pugixml)
    - pkgconfig(python3)
    - pkgconfig(sdl2)
    - pkgconfig(sndfile)
    - pkgconfig(xi)
    - pkgconfig(xrender)
    - pkgconfig(xxf86vm)
    - alembic-devel
    - embree-devel
    - intel-tbb-devel
    - libboost-devel
    #- libharu-devel # Uncomment this for PDF support after 2.93 is released
    - libusd-devel
    - llvm-devel
    - numpy
    - potrace-devel
    - opencollada-devel
    - openimagedenoise-devel
    - opensubdiv-devel
    - openvdb-devel
rundeps    :
    - opencollada
clang      : yes
setup      : |
    %patch -p1 < $pkgfiles/LibUsd-version-21_x.patch
    %patch -p1 < $pkgfiles/OpenEXR-instead-of-ilmbase.patch

    %cmake_ninja \
        -DPYTHON_VERSION=%python3_version% \
        -DPYTHON_LIBPATH=%libdir% \
        -DPYTHON_LIBRARY=python%python3_version% \
        -DPYTHON_INCLUDE_DIR=/usr/include/python%python3_version% \
        -DWITH_ALEMBIC=ON \
        -DWITH_CODEC_FFMPEG=ON \
        -DWITH_CODEC_SNDFILE=ON \
        -DWITH_CYCLES_EMBREE=ON \
        -DWITH_CYCLES_OSL=ON \
        -DWITH_FFTW3=ON \
        -DWITH_IMAGE_OPENJPEG=ON \
        -DWITH_INSTALL_PORTABLE=OFF \
        -DWITH_JACK=ON \
        -DWITH_LLVM=ON \
        -DWITH_OPENCOLORIO=ON \
        -DWITH_OPENIMAGEIO=ON \
        -DWITH_OPENSUBDIV=ON \
        -DWITH_OPENVDB=ON \
        -DWITH_POTRACE=ON \
        -DWITH_PYTHON_INSTALL=OFF \
        -DWITH_SDL=ON \
        -DWITH_SYSTEM_GLEW=ON \
        -DWITH_SYSTEM_LZO=ON \
        -DWITH_USD=ON \
        -DWITH_X11_XINPUT=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -r $installdir/usr/share/doc/blender/license/
