name       : blender
version    : 2.83.5
release    : 48
source     :
    - https://download.blender.org/source/blender-2.83.5.tar.xz : 835ca58f4ff12f21f43ea77ddbabd80cba320952fb2cb39a83a928003ce5ca77
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : A fully integrated 3D graphics creation suite
description: |
    Blender is the free and open source 3D creation suite. It supports the entirety of the 3D pipeline—modeling, rigging, animation, simulation, rendering, compositing and motion tracking, even video editing and game creation.
builddeps  :
    - pkgconfig(OpenColorIO)
    - pkgconfig(OpenEXR)
    - pkgconfig(fftw3f)
    - pkgconfig(freetype2)
    - pkgconfig(glew)
    - pkgconfig(jack)
    - pkgconfig(jemalloc)
    - pkgconfig(libavcodec)
    - pkgconfig(libopenjp2)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(lzo2)
    - pkgconfig(openal)
    - pkgconfig(python3)
    - pkgconfig(sdl2)
    - pkgconfig(sndfile)
    - pkgconfig(xi)
    - pkgconfig(xrender)
    - pkgconfig(xxf86vm)
    - intel-tbb-devel
    - libboost-devel
    - llvm-devel
    - numpy
    - opencollada-devel
    - openimagedenoise-devel
    - openimageio-devel
    - opensubdiv-devel
clang      : yes
setup      : |
    %cmake_ninja \
        -DPYTHON_LIBPATH=%libdir% \
        -DPYTHON_LIBRARY=python%python3_version%m \
        -DPYTHON_INCLUDE_DIR=/usr/include/python%python3_version%m \
        -DWITH_CODEC_FFMPEG=ON \
        -DWITH_CODEC_SNDFILE=ON \
        -DWITH_FFTW3=ON \
        -DWITH_IMAGE_OPENJPEG=ON \
        -DWITH_INSTALL_PORTABLE=OFF \
        -DWITH_JACK=ON \
        -DWITH_LLVM=ON \
        -DWITH_OPENCOLORIO=ON \
        -DWITH_OPENSUBDIV=ON \
        -DWITH_PYTHON_INSTALL=OFF \
        -DWITH_SDL=ON \
        -DWITH_SDL_DYNLOAD=ON \
        -DWITH_SYSTEM_GLEW=ON \
        -DWITH_SYSTEM_LZO=ON \
        -DWITH_SYSTEM_OPENJPEG=ON \
        -DWITH_X11_XINPUT=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
