name       : blender
version    : 2.74
release    : 1
source     :
    - http://download.blender.org/source/blender-2.74.tar.gz : 0ca3ceb6c656ae7c556f81ab0994e6aa7a6c64324824cbc94a87caf36f0a119d
license    : GPL-2.0+
summary    : A fully integrated 3D graphics creation suite
description: |
    A fully integrated 3D graphics creation suite
builddeps  :
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
