name       : blender
version    : 2.78c
release    : 19
source     :
    - http://download.blender.org/source/blender-2.78c.tar.gz : 64a98ff30300f79385ddb9ad016aa790a92720ff2feb84ddb1d097e6531dd338
license    : GPL-2.0+
component  : multimedia.graphics
summary    : A fully integrated 3D graphics creation suite
description: |
    A fully integrated 3D graphics creation suite
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(libpng)
    - pkgconfig(python-3.5)
    - pkgconfig(OpenEXR)
    - pkgconfig(libtiff-4)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(libopenjpeg1)
    - pkgconfig(OpenColorIO)
    - pkgconfig(fftw3f)
    - pkgconfig(libavcodec)
    - pkgconfig(sndfile)
    - pkgconfig(glew)
    - pkgconfig(xi)
    - libjpeg-turbo-devel
    - jemalloc-devel
    - libboost-devel
    - openimageio-devel
    - llvm-devel
setup      : |
    mkdir build && pushd build
    # Need python3.4 for blender, gotta get this updated (task4 ikey)
    # Lots of enabling to do here, system glew, bullet, openjpeg, gameengine, etc..
    # importantly: fix clang, get llvm working here.
    %cmake .. \
        -DPYTHON_LIBPATH=%libdir% \
        -DPYTHON_LIBRARY=python3.5m \
        -DPYTHON_INCLUDE_DIR=/usr/include/python3.5m \
        -DWITH_SYSTEM_GLEW=no \
        -DWITH_INSTALL_PORTABLE=OFF \
        -DWITH_PYTHON_INSTALL=OFF \
        -DWITH_SDL=ON \
        -DWITH_IMAGE_OPENJPEG=ON \
        -DWITH_SYSTEM_OPENJPEG=ON \
        -DWITH_OPENCOLORIO=ON \
        -DWITH_FFTW3=ON \
        -DWITH_X11_XINPUT=ON \
        -DWITH_SDL_DYNLOAD=ON \
        -DWITH_CODEC_FFMPEG=ON \
        -DWITH_CODEC_FFMPEG=ON \
        -DWITH_CODEC_SNDFILE=ON \
        -DWITH_SYSTEM_GLEW=ON \
        -DDWITH_LLVM=ON
build      : |
    pushd build
    %make
install    : |
    pushd build
    %make_install
    popd
